version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:6006
    depends_on:
      - phoenix

  phoenix:
    build:
      context: .
      dockerfile: Dockerfile.phoenix
    ports:
      - "6006:6006"
    volumes:
      - phoenix_data:/data/phoenix

volumes:
  phoenix_data: 