providers:
  openai:
    api_base: "https://api.openai.com/v1"
    models:
      - name: "gpt-4o"
      - name: "gpt-4o-mini"

  anthropic:
    api_base: "https://api.anthropic.com"
    models:
      - name: "claude-2"
      - name: "claude-instant-1"

  azure:
    api_base: "https://droid-m9nk6ek2-eastus2.cognitiveservices.azure.com/"
    api_version: "2025-03-01-preview" # TODO: Need to support multiple api versions
    models:
      - name: "gpt-4.1-mini"

  gemini:
    api_base: "https://generativelanguage.googleapis.com"
    models:
      - name: "gemini-1.5-flash-002"
      - name: "gemini-2.0-flash-lite"